"""increase result_json capacity

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-21 17:28:12.734856
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'result_json',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_subscriptions_stripe_customer'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_stripe_customer'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.alter_column('reports', 'result_json',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
